import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Introduction from '../components/Introduction'
import NavBar from '../components/Navbar'
import Portfolio from '../components/Portfolio'
import SkillsAndTools from '../components/SkillsAndTools'
import Services from '../components/Services'
import ContactMe from '../components/ContactMe'
import Footer from '../components/Footer'





export default function Home() {
  return (
    <div className="grid">
      <Head>
        <title>James Peters | Software Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <Introduction/>
      <Portfolio/>
      <SkillsAndTools/>
      <Services/>
      <ContactMe/>
      <Footer/>
    </div>
  )
}
